# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-22 22:44
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import red.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ocurrencia', models.DateField()),
                ('hora_ocurrencia', models.TimeField()),
                ('tipo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('areas', models.ManyToManyField(to='red.AreaConocimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('tipo', models.IntegerField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Actividad')),
                ('id_comentario_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_respuesta', to='red.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Compartir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('visibilidad', models.IntegerField()),
                ('id_actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Actividad')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NivelFormacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=100)),
                ('titulo_obtenido', models.CharField(max_length=30)),
                ('competencias_adquiridas', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('tipo_formacion', models.IntegerField()),
                ('nivel_educativo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('contenido', models.TextField()),
                ('imagenes', models.ImageField(upload_to=red.models.user_directory_path_images)),
                ('audio', models.FileField(upload_to=red.models.user_directory_path_audio)),
                ('video', models.FileField(upload_to=red.models.user_directory_path_videos)),
                ('fecha_creacion', models.DateField()),
                ('hora_creacion', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=254)),
                ('descripcion', models.TextField()),
                ('permisos', models.ManyToManyField(to='red.Permiso')),
            ],
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField()),
                ('fecha_actividad', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombres', models.CharField(max_length=254)),
                ('apellidos', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.TextField()),
                ('telefono_movil', models.CharField(max_length=20)),
                ('telefono_fijo', models.CharField(max_length=20)),
                ('telefono_oficina', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='red.Usuario')),
                ('intereses', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('foto_perfil', models.ImageField(upload_to=red.models.user_directory_profile_picture)),
                ('url_facebook_perfil', models.URLField()),
                ('url_twitter_perfil', models.URLField()),
                ('areas', models.ManyToManyField(to='red.AreaConocimiento')),
                ('idiomas', models.ManyToManyField(to='red.Idioma')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(to='red.Rol'),
        ),
        migrations.AddField(
            model_name='seguidor',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Usuario'),
        ),
        migrations.AddField(
            model_name='post',
            name='id_canal',
            field=models.ManyToManyField(blank=True, to='red.Canal'),
        ),
        migrations.AddField(
            model_name='canal',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Usuario', unique=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='autor_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Usuario'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='id_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Post'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='seguidores',
            field=models.ManyToManyField(blank=True, to='red.Seguidor'),
        ),
        migrations.AddField(
            model_name='nivelformacion',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Perfil'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='id_autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='red.Perfil'),
        ),
        migrations.AddField(
            model_name='canal',
            name='miembros',
            field=models.ManyToManyField(to='red.Perfil'),
        ),
    ]
