# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-07 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='nombre',
            field=models.TextField(default='nombre', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='canal',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='red.AreaConocimiento'),
        ),
        migrations.AlterField(
            model_name='canal',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='red.Usuario', unique=True),
        ),
        migrations.AlterField(
            model_name='canal',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
