# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import red.models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0006_auto_20170212_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to=red.models.user_directory_profile_picture),
        ),
    ]
