# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0007_auto_20170212_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to='red.Usuario'),
        ),
    ]
