# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-12 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0009_auto_20170212_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='idiomas',
            field=models.ManyToManyField(related_name='idiomas', to='red.Idioma'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner', serialize=False, to='red.Usuario'),
        ),
    ]
