# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-19 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import red.models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0011_auto_20170212_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=red.models.user_directory_path_audio),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to=red.models.user_directory_path_images),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=red.models.user_directory_path_videos),
        ),
    ]
