# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-26 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0014_auto_20170325_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canal',
            name='areas',
            field=models.ManyToManyField(related_name='areas', to='red.AreaConocimiento'),
        ),
    ]
