# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0020_auto_20170328_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publicacion', to='red.Post'),
        ),
    ]
