# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-29 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0022_auto_20170328_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
